### ISSUE TITLE
Correction (Not By PR)

### ISSUE THREAD

**Issue by TheDeibo** [JiangHtml/moving-text#1]
I am not going to correct you by Pull request, because this is too small, so ill correct by issue.
Look carefully. Do you see a problem? I do. 
```
<HTML>
    <BODY>
        <marquee>Edit This text here to make it</marquee
    </BODY>
</HTML>
```
Still dont see it? 
Well, here is the correction:

```
<HTML>
    <BODY>
        <marquee>Edit This text here to make it</marquee>
    </BODY>
</HTML>
```
The Solution was, END THE TAGS!!!
A great place to go is http://www.w3schools.com/html (theres even Marquees there!!!)

**Comment by jiang11** [comment]
😫 so small. '>'

**Comment by TheDeibo** [comment]
I don't know how I found this, but HA... im sooo glad I did... to correct this xD
